# DDO4MLA Seminar 2: NumPy Tutorial

## Introduction

Welcome back to DDO4MLA. This is the second tutorial, and today, we would like to demonstrate how to work with NumPy.

To study this tutorial, please execute all of the code cells and analyze the output.

NumPy is a Python library that provides a convenient interface for handling arrays. It offers a feature known as vectorization, which enables applying operations to the entire array of values at once. This, of course, has a positive impact on the speed of computation.

Moreover, NumPy utilizes less memory for array storage, has pre-built mathematical operations, and many other useful features.

Therefore, one might ask why we need NumPy when we already have Python's built-in list class. The answer is that NumPy's advantages, including vectorization, make it a more efficient option for handling arrays.

Now, let us import the NumPy package.

In [1]:
import numpy as np

## Array creation

The most important part of the package is the **ndarray** class, instances of which are a **n**-dimensional arrays.

Let's create 3x3 two-dimensional array using the ndarray class, then print it

In [2]:
a = np.array([[1,2,3], [4,5,6], [7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Let's take a look at its shape. 

In [3]:
a.shape

(3, 3)

Now let's create a three-dimensional array 

In [4]:
b = np.array([[[1,2,3],[4,5,6]], [[7,8,9],[10,11,12]]])
b

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [5]:
b.shape

(2, 2, 3)

As you can see, the dimension that corresponds to the depth is the first one.

We can obtain the same array using **arange** and **reshape** methods. 

Method `arange(start,stop,step)` generates 1 dim array beginning with `start` value, ending with but not including `stop` value, with step = `step`. By default `step` = 1.

In [6]:
np.arange(1, 9, 2)

array([1, 3, 5, 7])

Method `reshape(shape)` changes array shape, by flattening it to a row, and filling new array of given form `shape` with values from this row. 
So we can get our `a` and `b` arrays now, using these methods.

In [7]:
a = np.arange(1,10).reshape((3,3))
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
b = np.arange(1,13).reshape((2,2,3))
b

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

We also can create:
*   identity matrix and its analogues




In [9]:
np.eye(3, 3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [10]:
np.eye(6, 4, k=-1)

array([[0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

- Diagonal matrix of a given sequence 


In [11]:
np.diag((1, 2, 3))

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

- Diagonal of a given matrix

In [12]:
np.diag(a)

array([1, 5, 9])

*   an array of given form filled with zeros


In [13]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

*   an array of given form filled with units

In [14]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

*   an array of given form filled with a given value

In [15]:
np.full((3,3), 7)

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

## Array indexing 



Numpy uses a standard indexing method that works on subset selection. It has folowing syntax:

`a[start:stop:step=1]`

which means, that from array `a` will be selected subarray begining with `start` index, ending with but not including `stop` index, with step = `step` set by defaul to 1. 

i.e. `a[start]`, `a[start + step]`, `a[start + 2*step]`, ...

The first index of any array is always `0` that's why using a single index for instance `a[2]` will actually call the 3rd element of the array. 

In [16]:
a = np.arange(1,10)
print("Following array ", a, "has")
print("the first element with index = 0 equal to", a[0])
print("the second element with index = 1 equal to", a[1])
print("the last element with index = 8 equal to", a[8])

Following array  [1 2 3 4 5 6 7 8 9] has
the first element with index = 0 equal to 1
the second element with index = 1 equal to 2
the last element with index = 8 equal to 9


Consider the following example. Accroding to the indexing `0:3` the elements with indices `0`, `1` and `2` should be taken, i.e. the first three elements of the array. The element having index `3` is not included as it only indicates the boundary of the selection.

In [17]:
a[0:3]

array([1, 2, 3])

Now consider the indexing `0:4:2`. Since the step is equal to two the elements to be taken are `0` and `2`. The element with index `4` is not included by the same reason as in the previous example.

In [18]:
a[0:4:2]

array([1, 3])

Let's see how it works with 2-dim array. 


In [19]:
b = np.arange(1,10).reshape((3,3))
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
b[0,0]

1

In [21]:
b[0]

array([1, 2, 3])

In [22]:
b[0,0:3]

array([1, 2, 3])

In [23]:
b[0:3,2]

array([3, 6, 9])

We can use negative indices in order to obtain elements in the opposite direction, i.e., starting from the end.

In [24]:
b[0,-3]

1

In [25]:
b[-3,0]

1

We can use `:`, in order to obtain all elements of the dimension, where we put `:`. 

In [26]:
b[0,:]

array([1, 2, 3])

In [27]:
b[:,2]

array([3, 6, 9])

When indexing numpy array using `:` you have to remember one important thing: notations `b[:, 0:1]` and `b[:, 0]` return the same values of the array `b`, but the outputs will have different shapes.

In [28]:
print(b[0, :])
print(b[0, :].shape)

[1 2 3]
(3,)


In [29]:
print(b[0:1, :])
print(b[0:1, :].shape)

[[1 2 3]]
(1, 3)


This means, that `b[0, :]` is a one-dimensional array, i.e., a row-vector, but `b[0:1, :]` is a two-dimensional array, i.e., a 
matrix with only one row. 

## Operations with arrays

### Arithmetic and logical

The basic arithmetic and logical operations on arrays perform **elementwise** operations,  i.e. operations on elements of arrays, that have the same **indices**. It also means, that arrays must have the same shape. So they are the same operators as for scalars:

```
+  Addition
-  Subtraction
*  Multiplication
/  Float division 
// Floor division (remainder is removed)
%  Modulus (returns remainder of devision)
** Exponent (raises the first operand to a degree equal to the second operand)
<  Greater than
<= Less than or equal to
== Equal to
>= Greater than or equal to
>  Less than
!= Not equal to
```


In [30]:
c = np.arange(1,10)
c

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
d = np.full(9, 2)
d

array([2, 2, 2, 2, 2, 2, 2, 2, 2])

In [32]:
c + d

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11])

In [33]:
c // d

array([0, 1, 1, 2, 2, 3, 3, 4, 4])

In [34]:
c % d

array([1, 0, 1, 0, 1, 0, 1, 0, 1])

In [35]:
c ** d

array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])

In [36]:
c <= d

array([ True,  True, False, False, False, False, False, False, False])

In [37]:
c != d

array([ True, False,  True,  True,  True,  True,  True,  True,  True])

If one of the operands specifies a number (scalar), resulting array will be of the same shape as the array operand. 

In [38]:
2 * c

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [39]:
c != 1

array([False,  True,  True,  True,  True,  True,  True,  True,  True])

### ndarray methods

Now let's take a look at commonly used methods of ndarray class.

*   `array.flatten()`

**Reshapes** the matrix into a vector


In [40]:
f = np.arange(1,10).reshape((3,3))
f

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [41]:
f.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

*   `array.min(axis=None) `
*   `array.max(axis=None)`
*   `array.mean(axis=None)`
*   `array.std(axis=None)`

along given axis (axis = 0 - column-wise, axis = 1 - row-wise) return **minimum** and **maximum** values, arithmetic **mean** and **standard deviation**. If the axis is not set, the values will be found for the whole array.

In [42]:
f

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [43]:
f.min(axis=0)

array([1, 2, 3])

In [44]:
f.min(axis=1)

array([1, 4, 7])

In [45]:
f.max()

9

In [46]:
f.mean(axis=0)

array([4., 5., 6.])

In [47]:
f.std()

2.581988897471611

*   `array.argmin(axis=None)`
*   `array.argmax(axis=None)`

return the **indices of the maximum and minimum elements** in an array

In [48]:
f

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [49]:
f.argmin()

0

In [50]:
f.argmax(axis=0)

array([2, 2, 2], dtype=int64)

*   `np.sum(array, axis=None)`

**Sum of elements** over given axis.

If axis=None it finds the sum over whole array


In [51]:
np.sum(f)

45

In [52]:
np.sum(f, axis=0)

array([12, 15, 18])

Here it's also important to know, that computed array has vector shape. 

In [53]:
np.sum(f, axis=0).shape

(3,)

In order to keep matrix shape, set parameter `keepdims` to `True`

In [54]:
np.sum(f, axis=0, keepdims= True).shape

(1, 3)

### Linear algebra

**Arrays transpose**

*   `array.T` 

In [55]:
h = np.arange(1,7).reshape(2,3)
h

array([[1, 2, 3],
       [4, 5, 6]])

In [56]:
h.T

array([[1, 4],
       [2, 5],
       [3, 6]])

**Matrix norm**

By default Frobenius norm for matrices and L2 norm for vectors. 

*   `linalg.norm(array, ord=None)`


In [57]:
np.linalg.norm(h)

9.539392014169456

**Arrays multiplication**

There are two options:

1.   `array_1.dot(array_2)`

`dot` allows to compute 

*   Multiplication by scalars
*   Inner/scalar product of two vectros
*   Product of matrix and vector
*   Product of two matrices

2.   `np.matmul(array_1, array_2)` or `array_1@arrays_2`

`matmul` (@ operator) in comparison to `dot`

*   doesn't allow to multiplicate by scalars
*   if one of the array dimensions > 2, with other words if we have a tensor, it uses broadcasting to construct the answer. The resulting array will have lower dimensions, and accordingly it has smaller memory consumption. 

In [58]:
g = np.arange(7,19).reshape(3,4)
g

array([[ 7,  8,  9, 10],
       [11, 12, 13, 14],
       [15, 16, 17, 18]])

In [59]:
h.dot(g)

array([[ 74,  80,  86,  92],
       [173, 188, 203, 218]])

In [60]:
g.dot(2)

array([[14, 16, 18, 20],
       [22, 24, 26, 28],
       [30, 32, 34, 36]])

In [61]:
h@g

array([[ 74,  80,  86,  92],
       [173, 188, 203, 218]])

Array dimensions should meet the requirements of matrices multiplication: the number of columns of `array_1` must be equal to the number of rows of `array_2`. The following code thus produces an error.

In [62]:
g.dot(h)

ValueError: shapes (3,4) and (2,3) not aligned: 4 (dim 1) != 2 (dim 0)

**Rank of a matrix**
*   `np.linalg.matrix_rank(array)`

In [63]:
np.linalg.matrix_rank(h)

2

**Determinant of a matrix** 

*   `np.linalg.det(array)` 


In [64]:
e = np.array([[3,4], [2,9]])
e

array([[3, 4],
       [2, 9]])

In [65]:
np.linalg.det(e)

19.000000000000004

**Inverse matrix**
*   np.linalg.inv(array)

The squared matrix is invertible if:
*   rank = number of columns or rows
*   **determinant** != 0

In [66]:
np.linalg.matrix_rank(e)

2

In [67]:
np.linalg.inv(e)

array([[ 0.47368421, -0.21052632],
       [-0.10526316,  0.15789474]])

In [68]:
j = np.arange(9).reshape((3,3))
j

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [69]:
np.linalg.det(j)

0.0

The following code produces an error as the matrix determinant is zero meaning the matrix is not invertible.

In [70]:
np.linalg.inv(j)

LinAlgError: Singular matrix

**Eigenvalues and Eigenvector**:

*   Eigenvalues and right eigenvectors of a square array `np.linalg.eig(array)`
*   Eigenvalues of a non-symmetric array `np.linalg.eigvals(array)`
*   Eigenvalues and eigenvectors of a real symmetric or complex Hermitian (conjugate symmetric) array. `np.linalg.eigh(array)`
*   Eigenvalues of a real symmetric or complex Hermitian (conjugate symmetric) array `np.linalg.eigvalsh(array)`


In [71]:
lambd, v = np.linalg.eig(j)
print(lambd)
print(v)

[ 1.33484692e+01 -1.34846923e+00 -2.48477279e-16]
[[ 0.16476382  0.79969966  0.40824829]
 [ 0.50577448  0.10420579 -0.81649658]
 [ 0.84678513 -0.59128809  0.40824829]]


Each element of the eigenvalues vectors `lambd` is an eigenvalue. Each column of the eigenvector matrix `v` is an eigenvector. The first eigenvalue `lambd[0]` **corresponds** to the first **eigenvector** `v[:,0]` and so on. 

As you can see, the last eigenvalue is close to zero, thus, there are only two linearly independent eigenvectors that can be used as basis vectors.

Let's check **whether** they are indeed eigenvalues and right eigenvectors. The eigenvalue equation is:
$$Av=\lambda v$$

Where $A$ is a square matrix, $v$ is an eigenvector, and $\lambda$ is a corresponding eigenvalue. Let's take the first eigenvalue and corresponding eigenvector and then compute the left hand side and the right hand side of the equation above.

In [72]:
j.dot(v[:,0])

array([ 2.19934474,  6.75131503, 11.30328531])

In [73]:
lambd[0]*(v[:,0])

array([ 2.19934474,  6.75131503, 11.30328531])

As you can see they are equal meaning that the given vector is indeed an eigenvector of the given matrix.

**Power**

raises matrix `array` to a degree = `degree`

*   `np.linalg.matrix_power(array, degree)`


In [74]:
np.linalg.matrix_power(j, 2)

array([[ 15,  18,  21],
       [ 42,  54,  66],
       [ 69,  90, 111]])

## Exercises

Let's try to create our own neurons using NumPy.

Mathmatical description, inputs, weights, bias and output are given. You need to implement neurons in `#ToDo` sections of the template and get the same output as given. 

**Perceptron** 

$$ f(x,w,b)= \begin{cases} 1, \space w \cdot x + b > 0\\ 0, \space w \cdot x + b  \leqslant 0\\ \end{cases}$$

- $f(x,w,b)$ - activation function
- $x$ - inputs
- $w$ - weights
- $b$ - bias
- $ w \cdot x$ is inner/scalar product of $w$ and $x$

`x = (1.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0)`

`w = (0.87372833, 0.06451616, 0.15985972, 0.1768228 , 0.98192245, 0.99451061, 0.05185616, 0.4042013 , 0.28719303, 0.57638355)`

`b1 = - 2.39`, output: `f = 1` 



`b2 = - 2.40`, output: `f = 0` 

The solution must satisfy both biases 


In [75]:
import numpy as np
x = np.array([1.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0])
w = np.array([0.87372833, 0.06451616, 0.15985972, 0.1768228 , 0.98192245, 0.99451061, 0.05185616, 0.4042013 , 0.28719303, 0.57638355])
b1 = - 2.39 # output: f = 1
b2 = - 2.40 # output: f = 0

Complete the cell below by writing the code computing the perceptron's output.

In [76]:
def perceptron(x, w, b):
    # ToDo: Compute perceptron's output
    if (w.dot(x) + b) > 0:
        return 1
    else:
        return 0

Test your code by running the cells below.

In [77]:
perceptron(x, w, b1) # Should print 1

1

In [78]:
perceptron(x, w, b2) # Should print 0

0

**Sigmoid**
$$ f(x,w,b)= \sigma (w \cdot x + b)$$
$$ \sigma (a)=\frac{1}{1+e^{-a}} $$

The same `x` and `w` as for the perceptron

`b1 = - 2.39`, output: `f = 0.5016`

You may also need `np.exp(array)` method, that calculates the exponential of all array elements


In [79]:
def sigmoid(x, w, b):
    # ToDo: Compute the sigmoid function
    return 1 / (1 + np.exp(-w.dot(x) - b)) 

In [80]:
sigmoid(x, w, b1)

0.5016927260330166

**Hyperbolic tangent**
$$ f(x,w,b)= \tanh (w \cdot x + b)$$
$$ \tanh(a)=\frac{e^a-e^{-a}}{e^a+e^{-a}} $$

The same `x` and `w` as for the perceptron

`b1 = - 2.39`, output: `f = 0.006770`

Instead of `np.exp` use `np.tanh`

In [81]:
def hyp_tang(x, w, b):
    # ToDo: Compute the hyperbolic tangent
    return np.tanh(w.dot(x) + b)

In [82]:
hyp_tang(x, w, b1)

0.006770826529689403

**Softplus**

$$ f(x,w,b)= softplus (w \cdot x + b)$$
$$softplus(a) = ln(1 + e^a)$$

The same `x` and `w` as for the perceptron

`b1 = - 2.39`, output: `f = 0.6965`

Use `np.log` in order to calculate natural logarithm

In [83]:
def softplus(x, w, b):
    # ToDo: Compute the softplus function
    return np.log(1 + np.exp(w.dot(x) + b))

In [84]:
softplus(x, w, b1)

0.6965383762356315

Now, implement the neuron functions above inside python class Neuron

In [85]:
class Neuron():

    def __init__(self, x, w, b):
        self.x = x
        self.w = w
        self.b = b
        
    def perceptron(self):
        # ToDo: Compute perceptron's output
        if (self.w.dot(self.x) + self.b) > 0:
            return 1
        else:
            return 0

    def sigmoid(self):
        # ToDo: Compute the sigmoid function
        return 1 / (1 + np.exp(-self.w.dot(self.x) - self.b))

    def hyperbolic_tangent(self):
        # ToDo: Compute the hyperbolic tangent
        return np.tanh(self.w.dot(self.x) + self.b)

    def softplus(self):
        # ToDo: Compute the softplus function
        return np.log(1 + np.exp(self.w.dot(self.x) + self.b))

And check the solutions on the same inputs as before

In [86]:
my_neuron = Neuron(x, w, b2)

In [87]:
my_neuron.perceptron()

0

In [88]:
my_neuron = Neuron(x, w, b1)

In [89]:
my_neuron.perceptron()

1

In [90]:
my_neuron.sigmoid()

0.5016927260330166

In [91]:
my_neuron.hyperbolic_tangent()

0.006770826529689403

In [92]:
my_neuron.softplus()

0.6965383762356315